FROM jenkins/jenkins:lts
ENV DEBIAN_FRONTEND noninteractive
USER root
RUN apt-get update && apt-get install -yq \
    apt-transport-https ca-certificates curl \
    gnupg2 software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(cat /etc/os-release | perl -ne 'if (m/VERSION=.*\((.+)\)/) { print $1; }' ) stable" && \
    apt-get update && \
    apt-get install docker-ce-cli
